# Generated by Django 3.2.6 on 2021-08-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('address', models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Address')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Description')),
                ('type_room', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOBLE', 'Doble'), ('TRIPLE', 'Triple'), ('FAMILIAR', 'Familiar')], default=1, max_length=15, verbose_name='Type Room')),
                ('num_beds', models.IntegerField(default=1, verbose_name='Number of Beds')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied')], max_length=15)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('DELETED', 'Deleted')], max_length=15)),
                ('date', models.DateField(auto_now=True, verbose_name='Date Reservation')),
                ('date_end', models.DateField(auto_now=True, verbose_name='Date End Reservation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.room')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('monto', models.FloatField(default=0.0, verbose_name='Monto')),
                ('type_payment', models.CharField(choices=[('TDC', 'Tarjeta de credito'), ('TDB', 'Tarjeta de debito'), ('EFECTIVO', 'Efectivo')], max_length=15)),
                ('date', models.DateField(auto_now=True, verbose_name='Date Payment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
