# Generated by Django 3.2.6 on 2021-08-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_invoice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
