# Generated by Django 3.2.6 on 2021-08-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_invoice_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='room',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type_payment',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('CASH', 'Cash')], max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_room',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('DOUBLE', 'DoUble'), ('TRIPLE', 'Triple'), ('FAMILY', 'Family')], default=1, max_length=15, verbose_name='Type Room'),
        ),
    ]
